"use client";

import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Car, Clock, MapPin, Gauge } from 'lucide-react';

interface TrafficAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const TrafficAnalysisModal: React.FC<TrafficAnalysisModalProps> = ({ isOpen, onClose }) => {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="flex flex-col sm:max-w-[425px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <span className="flex items-center">
              <Car className="mr-2 h-5 w-5" /> Traffic Analysis
            </span>
          </DialogTitle>
          <DialogDescription>
            Here are some simulated traffic insights for the City of Torino:
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4 text-gray-700">
          <div className="flex items-center">
            <Clock className="mr-2 h-5 w-5 text-indigo-600" />
            <strong>Busiest Hours:</strong> 07:00–09:00 (Morning) & 17:00–19:00 (Evening)
          </div>
          <div className="flex items-center">
            <MapPin className="mr-2 h-5 w-5 text-red-600" />
            <strong>Most Congested Areas:</strong> Via Roma, Piazza Castello, Corso Vittorio Emanuele II
          </div>
          <div className="flex items-center">
            <Gauge className="mr-2 h-5 w-5 text-green-600" />
            <strong>Average Speed:</strong> 24 km/h
          </div>
          <p className="text-sm text-gray-500 mt-2">
            *This is simulated data. Actual analysis will be generated by the Python system.
          </p>
        </div>
        <DialogFooter className="sticky bottom-0 bg-white pt-4 border-t">
          <Button onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default TrafficAnalysisModal;