export interface OpenDataPortal {
  name: string;
  title: string;
  url: string;
  description: string;
  place: string;
  location: [number, number]; // [latitude, longitude]
  country: string;
  status: string;
}

export const openDataPortals: OpenDataPortal[] = [
  {
    name: "ann-arbor-data",
    title: "Ann Arbor, Michigan Open Data",
    url: "http://www.a2gov.org/data/Pages/default.aspx",
    description: "City of Ann Arbor's Open Data Catalog (USA).",
    place: "Ann Arbor, Michigan",
    location: [42.2808, -83.7430],
    country: "US",
    status: "active",
  },
  {
    name: "berlin-open-data",
    title: "Berlin Open Data",
    url: "http://daten.berlin.de/",
    description: "Official open data catalog of the Senate of Berlin, Germany.",
    place: "Berlin, Germany",
    location: [52.5200, 13.4050],
    country: "DE",
    status: "active",
  },
  {
    name: "amsterdam-open-data",
    title: "Amsterdam Open Data",
    url: "http://www.amsterdamopendata.nl/home",
    description: "Portal commissioned by the Amsterdam Economic Board Open Data Exchange (ODE).",
    place: "Amsterdam, Netherlands",
    location: [52.3676, 4.9041],
    country: "NL",
    status: "active",
  },
  {
    name: "london-datastore",
    title: "London Datastore",
    url: "http://data.london.gov.uk",
    description: "Data on London, UK from the GLA and other public sector bodies.",
    place: "Greater London, UK",
    location: [51.5074, -0.1278],
    country: "GB",
    status: "active",
  },
  {
    name: "sydney-open-data",
    title: "Sydney Open Data",
    url: "http://gong.io/", 
    description: "Open data initiative and platform for Wollongong, Shellharbour, Kiama and the greater Illawarra region (near Sydney, Australia).",
    place: "Sydney, Australia",
    location: [-33.8688, 151.2093],
    country: "AU",
    status: "active",
  },
  {
    name: "us-federal-data",
    title: "United States Federal Government Data",
    url: "http://www.data.gov/catalog",
    description: "The purpose of Data.gov is to increase public access to high value, machine readable datasets generated by the Executive Branch of the Federal Government.",
    place: "United States of America",
    location: [38.9072, -77.0369], // Washington D.C.
    country: "US",
    status: "active",
  },
  {
    name: "brazil-gov-data",
    title: "dados.gov.br - Brazilian Government Data",
    url: "http://dados.gov.br/",
    description: "Official Brazilian government data portal.",
    place: "Brazil",
    location: [-15.7801, -47.9292], // Brasília
    country: "BR",
    status: "active",
  },
  {
    name: "india-data-portal",
    title: "Data Portal India",
    url: "http://data.gov.in/",
    description: "Official data portal for the Government of India.",
    place: "India",
    location: [28.6139, 77.2090], // New Delhi
    country: "IN",
    status: "active",
  },
  {
    name: "eu-open-data-portal",
    title: "EU Open Data Portal",
    url: "http://open-data.europa.eu/",
    description: "Open Data portal for the European Commission and other institutions of the European Union.",
    place: "EU countries",
    location: [50.8503, 4.3517], // Brussels
    country: "EU",
    status: "active",
  },
  {
    name: "slovak-republic-data",
    title: "Slovak Republic National Data Portal",
    url: "http://data.gov.sk/",
    description: "A CKAN based portal for the Slovak Republic.",
    place: "Slovak Republic",
    location: [48.1486, 17.1077], // Bratislava
    country: "SK",
    status: "active",
  },
  {
    name: "japan-meti-data",
    title: "Open Data METI, Japan",
    url: "http://datameti.go.jp/",
    description: "Test site produced by METI, the Japanese Ministry for Economy, Trade and Industry.",
    place: "Japan",
    location: [35.6895, 139.6917], // Tokyo
    country: "JP",
    status: "active",
  },
  {
    name: "canada-data",
    title: "Canada Open Government Data",
    url: "http://www.data.gc.ca/",
    description: "Official open data portal for the Government of Canada.",
    place: "Canada",
    location: [45.4215, -75.6972], // Ottawa
    country: "CA",
    status: "active",
  },
];